//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_3_Marko_Gacinovic_Jasmina_Kostadinovic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIngredient
    {
        public int IngredientsID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> RecipeID { get; set; }
    
        public virtual tblRecipe tblRecipe { get; set; }
    }
}
