//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookbook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShoppingList
    {
        public int ShoppingListID { get; set; }
        public string IngredientName { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<bool> Owned { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> UserDataID { get; set; }
    
        public virtual tblRecipe tblRecipe { get; set; }
        public virtual tblUserData tblUserData { get; set; }
    }
}
